spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ccp.simple.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  lever:
    root: INFO