spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d2ddbtogjchc73djg6a0-a.singapore-postgres.render.com:5432/simple_iltf
    username: simple_iltf_user
    password: r0wIZhk0jQfnrezBZlfH6Xrv0myK9pH3
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ccp.simple.domain
  type-handlers-package: com.ccp.simple.handler
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG
