CREATE TABLE IF NOT EXISTS USER_INFO (
    ID VARCHAR(20) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    CREATE_DT TIMESTAMP,
    UPDATE_DT TIMESTAMP,
    ROLE VARCHAR(20) NOT NULL,
    REFRESH_TOKEN VARCHAR(254)
);
